### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by angus-lherrou** [Machine-Learning-for-Medical-Language/cnlp_transformers#26]
We've made a number of changes to this library since releasing v0.1.1 on PyPI in December (1154e29). We should decide what work we want to do before releasing a new version (say, v0.2.0).

To start with, I'll create a draft PR containing some housekeeping changes on top of the current master branch for v0.2.0, and we can go from there.

Tentative checklist (feel free to add; discuss at start of collaborative session):
- [x] Update REST scripts (#28)
- [x] Update README (#33)
- [x] Target Python >=3.7, <=3.8 (#31, #34) 
- [x] Update PyTorch dependency version (#37)
- [x] Fix pathing issue in `transform_uci_drug.py` (#41)
- [x] Fix missing anaforatools dependency (#40) 

Future:
- Clean up existing code: remove unused imports, discuss code style (use [Black](https://github.com/psf/black)? pre-commit hooks? GitHub Actions?)
- Automated testing (codecov?)
- BertViz (#11)
- DistilBERT support (#35)
- Documentation/ReadTheDocs (#9)

**Comment by angus-lherrou** [comment]
Spinning off DistilBERT support for future release

**Comment by angus-lherrou** [comment]
Separating documentation/ReadTheDocs from the release, to add in patch releases as docstrings are fleshed out and added

**Comment by angus-lherrou** [comment]
Spinning off BertViz support for future release
